import { SpriteProject } from '../types/sprite';

export interface QBasicExportOptions {
  exportType: 'game_put' | 'sub_data' | 'array_data';
  screenMode: '13' | '7' | '12';
  putMode: 'PSET' | 'XOR' | 'AND' | 'OR' | 'PRESET';
  varName: string;
  generateStarsBg: boolean;
}

export function generateQBasicCode(project: SpriteProject, options: QBasicExportOptions): string {
  const { width, height, frames } = project;
  const cleanVar = (options.varName || project.name || 'SPRITE')
    .toUpperCase()
    .replace(/[^A-Z0-9_]/g, '')
    .slice(0, 14) || 'SPRITE';

  // Calculate size in bytes and integer array elements for SCREEN 13 (8 bits/pixel)
  // Byte size = 4 + (width * height)
  // Integer array size = INT((4 + width * height + 1) / 2)
  const bytesPerPixel = options.screenMode === '13' ? 1 : 0.5; // SCREEN 7/12 is 4 bits/pixel (planar)
  const totalBytesPerFrame = 4 + Math.ceil(width * height * bytesPerPixel);
  const intElementsPerFrame = Math.ceil(totalBytesPerFrame / 2);

  const lines: string[] = [];

  // Header comment
  lines.push(`' ==============================================================`);
  lines.push(`' QBASIC SPRITE: ${cleanVar}`);
  lines.push(`' Dimensions: ${width} x ${height} pixels | Frames: ${frames.length}`);
  lines.push(`' Generated by QBasic Sprite Editor for MS-DOS / QB64`);
  lines.push(`' ==============================================================`);
  lines.push(``);

  if (options.exportType === 'game_put') {
    // Generate complete interactive playable demo
    lines.push(`DEFINT A-Z`);
    lines.push(`SCREEN ${options.screenMode}`);
    lines.push(`COLOR 15, 0: CLS`);
    lines.push(``);

    if (frames.length > 1) {
      lines.push(`' Multi-frame sprite array: ${frames.length} frames, ${intElementsPerFrame} integers each`);
      lines.push(`DIM SHARED ${cleanVar}%(${frames.length - 1}, ${intElementsPerFrame - 1})`);
    } else {
      lines.push(`' Single sprite array: ${intElementsPerFrame} integers`);
      lines.push(`DIM SHARED ${cleanVar}%(${intElementsPerFrame - 1})`);
    }

    lines.push(``);
    lines.push(`PRINT "Loading ${cleanVar} into graphics memory..."`);
    lines.push(`GOSUB LoadSpriteData`);
    lines.push(`CLS`);
    lines.push(``);

    // Initial position & game loop
    lines.push(`' --- Interactive Test Game Loop ---`);
    lines.push(`x = 160 - ${Math.floor(width / 2)}`);
    lines.push(`y = 100 - ${Math.floor(height / 2)}`);
    lines.push(`oldX = x: oldY = y`);
    lines.push(`curFrame = 0`);
    lines.push(`frameTimer = 0`);
    lines.push(``);

    if (options.generateStarsBg) {
      lines.push(`' Draw retro starfield background`);
      lines.push(`FOR i = 1 TO 60`);
      lines.push(`  sx = INT(RND * 319)`);
      lines.push(`  sy = INT(RND * 190) + 10`);
      lines.push(`  sc = (INT(RND * 3) + 1) * 7 + 1`);
      lines.push(`  PSET (sx, sy), sc`);
      lines.push(`NEXT i`);
      lines.push(``);
    }

    lines.push(`LOCATE 1, 1: PRINT "Arrow Keys/WASD: Move | ESC: Quit";`);
    lines.push(``);

    lines.push(`MainLoop:`);
    lines.push(`  ' Wait for vertical retrace (smooth 60Hz timing in QBasic)`);
    lines.push(`  WAIT &H3DA, 8`);
    lines.push(`  WAIT &H3DA, 8, 8`);
    lines.push(``);

    if (frames.length > 1) {
      lines.push(`  ' Animate frames`);
      lines.push(`  frameTimer = frameTimer + 1`);
      lines.push(`  IF frameTimer > 6 THEN`);
      lines.push(`    frameTimer = 0`);
      lines.push(`    curFrame = (curFrame + 1) MOD ${frames.length}`);
      lines.push(`  END IF`);
      lines.push(``);
    }

    // Render sprite
    if (options.putMode === 'XOR') {
      lines.push(`  ' Erase previous position with XOR`);
      if (frames.length > 1) {
        lines.push(`  PUT (oldX, oldY), ${cleanVar}%, XOR`);
      } else {
        lines.push(`  PUT (oldX, oldY), ${cleanVar}%, XOR`);
      }
      lines.push(`  ' Draw new position with XOR`);
      if (frames.length > 1) {
        lines.push(`  PUT (x, y), ${cleanVar}%, XOR`);
      } else {
        lines.push(`  PUT (x, y), ${cleanVar}%, XOR`);
      }
    } else {
      // PSET
      if (options.generateStarsBg) {
        lines.push(`  ' Clear old sprite box area or redraw background`);
        lines.push(`  LINE (oldX, oldY)-(oldX + ${width - 1}, oldY + ${height - 1}), 0, BF`);
      } else {
        lines.push(`  LINE (oldX, oldY)-(oldX + ${width - 1}, oldY + ${height - 1}), 0, BF`);
      }
      lines.push(`  ' Draw sprite`);
      if (frames.length > 1) {
        lines.push(`  ' GET/PUT with frame index`);
        lines.push(`  ' Note: In QBasic, array slice or 1D offset is passed`);
        lines.push(`  PUT (x, y), ${cleanVar}%(curFrame, 0), ${options.putMode}`);
      } else {
        lines.push(`  PUT (x, y), ${cleanVar}%, ${options.putMode}`);
      }
    }

    lines.push(`  oldX = x: oldY = y`);
    lines.push(``);

    // Keyboard controls
    lines.push(`  k$ = INKEY$`);
    lines.push(`  IF k$ = CHR$(27) THEN GOTO EndGame  ' ESC`);
    lines.push(`  IF k$ = CHR$(0) + CHR$(72) OR k$ = "w" OR k$ = "W" THEN y = y - 2 ' Up`);
    lines.push(`  IF k$ = CHR$(0) + CHR$(80) OR k$ = "s" OR k$ = "S" THEN y = y + 2 ' Down`);
    lines.push(`  IF k$ = CHR$(0) + CHR$(75) OR k$ = "a" OR k$ = "A" THEN x = x - 2 ' Left`);
    lines.push(`  IF k$ = CHR$(0) + CHR$(77) OR k$ = "d" OR k$ = "D" THEN x = x + 2 ' Right`);
    lines.push(``);
    lines.push(`  ' Clamp to screen bounds`);
    lines.push(`  IF x < 0 THEN x = 0`);
    lines.push(`  IF x > ${320 - width} THEN x = ${320 - width}`);
    lines.push(`  IF y < 12 THEN y = 12`);
    lines.push(`  IF y > ${200 - height} THEN y = ${200 - height}`);
    lines.push(``);
    lines.push(`  GOTO MainLoop`);
    lines.push(``);
    lines.push(`EndGame:`);
    lines.push(`  SCREEN 0: WIDTH 80: CLS`);
    lines.push(`  PRINT "Program ended. QBasic Sprite Editor (C) MS-DOS"`);
    lines.push(`  END`);
    lines.push(``);

    // Subroutine to unpack sprite into graphics array
    lines.push(`' --------------------------------------------------------------`);
    lines.push(`' Unpack DATA statements into PUT/GET array`);
    lines.push(`' --------------------------------------------------------------`);
    lines.push(`LoadSpriteData:`);
    lines.push(`  RESTORE SpriteRawData`);
    frames.forEach((f, fIdx) => {
      lines.push(`  ' Frame ${fIdx + 1}: ${f.name}`);
      lines.push(`  CLS`);
      lines.push(`  FOR py = 0 TO ${height - 1}`);
      lines.push(`    FOR px = 0 TO ${width - 1}`);
      lines.push(`      READ col%`);
      lines.push(`      IF col% > 0 THEN PSET (px, py), col%`);
      lines.push(`    NEXT px`);
      lines.push(`  NEXT py`);
      if (frames.length > 1) {
        lines.push(`  GET (0, 0)-(${width - 1}, ${height - 1}), ${cleanVar}%(${fIdx}, 0)`);
      } else {
        lines.push(`  GET (0, 0)-(${width - 1}, ${height - 1}), ${cleanVar}%`);
      }
    });
    lines.push(`  RETURN`);
    lines.push(``);
  } else if (options.exportType === 'sub_data') {
    // Generate SUB DrawSprite(x, y) with DATA
    lines.push(`DEFINT A-Z`);
    lines.push(`DECLARE SUB Draw${cleanVar} (x AS INTEGER, y AS INTEGER, frame AS INTEGER)`);
    lines.push(``);
    lines.push(`SCREEN ${options.screenMode}: CLS`);
    lines.push(`' Example calling the subroutine:`);
    lines.push(`Draw${cleanVar} 150, 90, 0`);
    lines.push(`DO: LOOP WHILE INKEY$ = ""`);
    lines.push(`SCREEN 0: WIDTH 80: CLS: END`);
    lines.push(``);
    lines.push(`SUB Draw${cleanVar} (x AS INTEGER, y AS INTEGER, frame AS INTEGER)`);
    lines.push(`  RESTORE SpriteRawData`);
    lines.push(`  ' Skip to specified frame if multi-frame`);
    lines.push(`  totalPix = ${width * height}`);
    lines.push(`  FOR skip = 1 TO frame * totalPix`);
    lines.push(`    READ dummy%`);
    lines.push(`  NEXT skip`);
    lines.push(``);
    lines.push(`  FOR py = 0 TO ${height - 1}`);
    lines.push(`    FOR px = 0 TO ${width - 1}`);
    lines.push(`      READ col%`);
    lines.push(`      ' Color ${project.transparentColorIndex} is transparent`);
    lines.push(`      IF col% <> ${project.transparentColorIndex} THEN`);
    lines.push(`        PSET (x + px, y + py), col%`);
    lines.push(`      END IF`);
    lines.push(`    NEXT px`);
    lines.push(`  NEXT py`);
    lines.push(`END SUB`);
    lines.push(``);
  } else {
    // Export raw DATA statements for embedding
    lines.push(`' Dimensions: Width=${width}, Height=${height}, Frames=${frames.length}`);
    lines.push(`' Read loop example:`);
    lines.push(`' FOR y = 0 TO ${height - 1}: FOR x = 0 TO ${width - 1}: READ c%: PSET (startX + x, startY + y), c%: NEXT x: NEXT y`);
    lines.push(``);
  }

  // Raw DATA blocks
  lines.push(`SpriteRawData:`);
  frames.forEach((frame, fIdx) => {
    lines.push(`' --- Frame ${fIdx}: ${frame.name} ---`);
    for (let y = 0; y < height; y++) {
      const rowSlice = frame.pixels.slice(y * width, (y + 1) * width);
      const dataStr = rowSlice.join(', ');
      lines.push(`DATA ${dataStr}`);
    }
  });

  return lines.join('\r\n');
}
